### ISSUE TITLE
[BUG] Can not use Ansible module azure_rm_deployment_module

### ISSUE THREAD

**Issue by huytrantda** [Azure/CloudShell#241]
## To Reproduce
Create test.yaml as below

```
---
- name: Test playbook
  hosts: localhost
  connection: local
  gather_facts: no
  module_defaults:
   azure_rm_deployment:
    name: "{{ 'ansible-arm-%Y%m%dT%H%M%S' | strftime }}"
  tasks:
    - name: Sample task name
      azure_rm_deployment:
        state: absent
        subscription_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        resource_group_name: test

```
Then on cloudshell run command: `ansible-playbook test.yaml` then error happen like this:

![image](https://user-images.githubusercontent.com/103617605/188283561-4e7b34ca-cec4-4f0a-b99c-790ed23387ed.png)

Run with debug mode: `ansible-playbook test.yaml -vvv`
![image](https://user-images.githubusercontent.com/103617605/188283698-867255a7-6b03-44da-bb32-2eb49215a764.png)

## Observed Behavior
N/A

## Expected behavior

Should have run as normal 2 weeks ago.

## Is this specific to Cloud Shell?
N/A

## Interface information
N/A

## Additional context
Last two weeks i can run module azure_rm_deployment without any issues.
It seems a recent release cause the above issue: https://github.com/Azure/CloudShell/releases/tag/1.0.20220803.1.base.master.585b6c60

Tested on different azure accounts, same issue.
